namespace: oneidentity
name: safeguardcollection
version: 2.0.0
readme: README.md
authors:
  - "One Identity LLC <support@oneidentity.com>"
description: Provides plugins to integrate Ansible with Safeguard for Privileged Passwords
license:
  - "Apache-2.0"
tags:
  - oneidentity
  - safeguard
  - credential
  - lookup
dependencies: {}
repository: "https://github.com/OneIdentity/safeguard-ansible"
documentation: "https://github.com/OneIdentity/safeguard-ansible"
homepage: "https://github.com/OneIdentity/safeguard-ansible"
issues: "https://github.com/OneIdentity/safeguard-ansible/issues"
build_ignore:
  - tests/

